use crate::modules::types::*;

pub fn definition() -> ModuleDefinition {
    ModuleDefinition {
        id: "spell_access".to_string(),
        name: "Spell Access Editor".to_string(),
        description: "Edit which classes can use each spell".to_string(),
        dat_file: DatFile::BattleData,
        base_offset: 0x4AEA30,
        entry_count: 264,
        entry_size: 64,
        entry_names: vec![
            "None".to_string(),
            "Deadshot".to_string(),
            "Deadshot II".to_string(),
            "Deadshot III".to_string(),
            "Deadshot IV".to_string(),
            "Tornado".to_string(),
            "Tornado II".to_string(),
            "Tornado III".to_string(),
            "Tornado IV".to_string(),
            "Sylphide".to_string(),
            "Sylphide II".to_string(),
            "Aeroflux".to_string(),
            "Aeroflux II".to_string(),
            "Instill Air".to_string(),
            "Aerogaurd".to_string(),
            "Whirlwind".to_string(),
            "Gaurding Gale".to_string(),
            "Balmy Breeze".to_string(),
            "Black Williwaw".to_string(),
            "Vulcan Lance".to_string(),
            "Vulcan Lance II".to_string(),
            "Vulcan Lance III".to_string(),
            "Vulcan Lance IV".to_string(),
            "Cragfall".to_string(),
            "Cragfall II".to_string(),
            "Cragfall III".to_string(),
            "Cragfall IV".to_string(),
            "Gnome".to_string(),
            "Gnome II".to_string(),
            "Earthquake".to_string(),
            "Earthquake II".to_string(),
            "Instill Earth".to_string(),
            "Petrogaurd".to_string(),
            "Protect".to_string(),
            "Blade Ward".to_string(),
            "Duststorm".to_string(),
            "Petrifog".to_string(),
            "Lightning Bow".to_string(),
            "Lightning Bow II".to_string(),
            "Lightning Bow III".to_string(),
            "Lightning Bow IV".to_string(),
            "Thunderflare".to_string(),
            "Thunderflare II".to_string(),
            "Thunderflare III".to_string(),
            "Thunderflare IV".to_string(),
            "Thunderbird".to_string(),
            "Thunderbird II".to_string(),
            "Thunderburst".to_string(),
            "Thunderburst II".to_string(),
            "Instill Lightning".to_string(),
            "Electricgaurd".to_string(),
            "Galvanize".to_string(),
            "Stormspark".to_string(),
            "Stunbomb".to_string(),
            "Stunslay".to_string(),
            "Aquablast".to_string(),
            "Aquablast II".to_string(),
            "Aquablast III".to_string(),
            "Aquablast IV".to_string(),
            "Acid Rain".to_string(),
            "Acid Rain II".to_string(),
            "Acid Rain III".to_string(),
            "Acid Rain IV".to_string(),
            "Undine".to_string(),
            "Undine II".to_string(),
            "Dread Vapor".to_string(),
            "Dread Vapor II".to_string(),
            "Instill Water".to_string(),
            "Aqaugaurd".to_string(),
            "Quench".to_string(),
            "Stagnate".to_string(),
            "Poison Mist".to_string(),
            "Sludgebind".to_string(),
            "Sparksphere".to_string(),
            "Sparksphere II".to_string(),
            "Sparksphere III".to_string(),
            "Sparksphere IV".to_string(),
            "Firestorm".to_string(),
            "Firestorm II".to_string(),
            "Firestorm III".to_string(),
            "Firestorm IV".to_string(),
            "Salamander".to_string(),
            "Salamander II".to_string(),
            "Supernova".to_string(),
            "Supernova II".to_string(),
            "Instill Fire".to_string(),
            "Pryogaurd".to_string(),
            "Flame Fusion".to_string(),
            "Pyrocrlastic Flow".to_string(),
            "Misery".to_string(),
            "Brimstone".to_string(),
            "Iceblast".to_string(),
            "Iceblast II".to_string(),
            "Iceblast III".to_string(),
            "Iceblast IV".to_string(),
            "Avalanche".to_string(),
            "Avalanche II".to_string(),
            "Avalanche III".to_string(),
            "Avalanche IV".to_string(),
            "Wendigo".to_string(),
            "Wendigo II".to_string(),
            "Ice Requiem".to_string(),
            "Ice Requiem II".to_string(),
            "Instill Ice".to_string(),
            "Frost Gaurd".to_string(),
            "Icy Focus".to_string(),
            "Indomitable Will".to_string(),
            "Numbing Cold".to_string(),
            "Freezing Gust".to_string(),
            "Spiritsurge".to_string(),
            "Spiritsurge II".to_string(),
            "Spiritsurge III".to_string(),
            "Spiritsurge IV".to_string(),
            "Judgement".to_string(),
            "Judgement II".to_string(),
            "Judgement III".to_string(),
            "Judgement IV".to_string(),
            "Wisplight".to_string(),
            "Wisplight II".to_string(),
            "Heavenly Judge".to_string(),
            "Heavenly Judge II".to_string(),
            "Exorcism".to_string(),
            "Exorcism II".to_string(),
            "Instill Light".to_string(),
            "Light guard".to_string(),
            "Silent Light".to_string(),
            "Boon of Swiftness".to_string(),
            "Dispel".to_string(),
            "Awaken".to_string(),
            "Awaken II".to_string(),
            "Innervate".to_string(),
            "Singing Light".to_string(),
            "Awaken Stone".to_string(),
            "Liberate".to_string(),
            "Cleanse".to_string(),
            "Cleanse II".to_string(),
            "Unburden".to_string(),
            "Decurse".to_string(),
            "Hearten".to_string(),
            "Ease".to_string(),
            "Heal".to_string(),
            "Heal II".to_string(),
            "Heal III".to_string(),
            "Heal IV".to_string(),
            "Major Heal".to_string(),
            "Major Heal II".to_string(),
            "Major Heal III".to_string(),
            "Resurrect".to_string(),
            "Resurrect II".to_string(),
            "Word of Pain".to_string(),
            "Word of Pain II".to_string(),
            "Word of Pain III".to_string(),
            "Word of Pain IV".to_string(),
            "Meteor Strike".to_string(),
            "Meteor Strike II".to_string(),
            "Meteor Strike III".to_string(),
            "Meteor Strike IV".to_string(),
            "Hellbound".to_string(),
            "Hellbound II".to_string(),
            "Abyss".to_string(),
            "Abyss II".to_string(),
            "Drain Heart".to_string(),
            "Drain Mind".to_string(),
            "Drain Power".to_string(),
            "Instill Shadow".to_string(),
            "Shadow Gaurd".to_string(),
            "Spellcharge".to_string(),
            "Paradigm Shift".to_string(),
            "Torpor".to_string(),
            "Petriburst".to_string(),
            "Paralytic Wave".to_string(),
            "Poison Cloud".to_string(),
            "None".to_string(),
            "Sleep".to_string(),
            "Charm".to_string(),
            "Dominate".to_string(),
            "Shackle".to_string(),
            "Fixate".to_string(),
            "Gravity Flux".to_string(),
            "Deadscream".to_string(),
            "Dead Mans Ivy".to_string(),
            "Tempest".to_string(),
            "Tempest II".to_string(),
            "Gaia Strike".to_string(),
            "Gaia Strike II".to_string(),
            "Vortex".to_string(),
            "Vortex II".to_string(),
            "Deluge".to_string(),
            "Deluge II".to_string(),
            "Annihilation".to_string(),
            "Annihilation II".to_string(),
            "Iceover".to_string(),
            "Iceover II".to_string(),
            "Starfall".to_string(),
            "Starfall II".to_string(),
            "Diablo's Spite".to_string(),
            "Diablo's Spite II".to_string(),
            "Palace Guide Book".to_string(),
            "Detect".to_string(),
            "Springboard".to_string(),
            "Teleport".to_string(),
            "Palace Guide Book II".to_string(),
            "Gift of Restoration".to_string(),
            "Gift of Renewal".to_string(),
            "Nullify Strike".to_string(),
            "Negate Spell".to_string(),
            "Dodge Blades".to_string(),
            "Ballistics".to_string(),
            "Enlighten".to_string(),
            "Phantom Shell".to_string(),
            "Holy Shield".to_string(),
            "Sacrifice".to_string(),
            "None".to_string(),
            "Living Corpse".to_string(),
            "Banish".to_string(),
            "Curse".to_string(),
            "Curse II".to_string(),
            "Curse III".to_string(),
            "Tainted Love".to_string(),
            "Prodigize".to_string(),
            "Breed Suspicion".to_string(),
            "Phantom Pain".to_string(),
            "Life Force".to_string(),
            "Putrify".to_string(),
            "Putrify II".to_string(),
            "Brain Rot".to_string(),
            "Summon Darkness".to_string(),
            "Black Plume".to_string(),
            "Styx Shift".to_string(),
            "Wind Dervish".to_string(),
            "Wind Dervish II".to_string(),
            "Sand Spider".to_string(),
            "Sand Spider II".to_string(),
            "Chimaera".to_string(),
            "Chimaera II".to_string(),
            "Water Tiger".to_string(),
            "Water Tiger II".to_string(),
            "Fire Snake".to_string(),
            "Fire Snake II".to_string(),
            "Rime Raven".to_string(),
            "Rime Raven II".to_string(),
            "Shadowbind".to_string(),
            "Palace Guide Book III".to_string(),
            "Leaping Monkey".to_string(),
            "Waterstep".to_string(),
            "Decoy".to_string(),
            "Bridle".to_string(),
            "Benumb".to_string(),
            "Envenom".to_string(),
            "Lion Dance".to_string(),
            "Harvest Dance".to_string(),
            "Bellows Dance".to_string(),
            "Shriving Dance".to_string(),
            "Comely Dance".to_string(),
            "Bedeviling Dance".to_string(),
            "Invirogating Dance".to_string(),
            "Demonpetal Dance".to_string(),
            "Ardent Conga".to_string(),
            "Weakening Joropo".to_string(),
            "Taunting Mambo".to_string(),
            "Stiring Folclore".to_string(),
            "Somber Chacarera".to_string(),
            "Escalating Sanat".to_string(),
            "Poised Arabesque".to_string(),
        ],
        fields: vec![
            FieldDefinition {
                name: "All Magic Set".to_string(),
                offset: 0,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Wizard Magic Set".to_string(),
                offset: 1,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Cleric Magic Set".to_string(),
                offset: 2,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Valkyrie Magic Set".to_string(),
                offset: 3,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Knight Magic Set".to_string(),
                offset: 4,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Terror Knight Magic Set".to_string(),
                offset: 5,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Swordmaster Magic Set".to_string(),
                offset: 6,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Ninja Magic Set".to_string(),
                offset: 7,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Warlock Magic Set".to_string(),
                offset: 8,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Necromancer Magic Set".to_string(),
                offset: 9,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Lich Magic Set".to_string(),
                offset: 10,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Divine Knight Magic Set".to_string(),
                offset: 11,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Patriarch Magic Set".to_string(),
                offset: 12,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Familiar Magic Set".to_string(),
                offset: 13,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Cyclops Magic Set".to_string(),
                offset: 14,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Boggart Magic Set".to_string(),
                offset: 15,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "None? Magic Set".to_string(),
                offset: 16,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Lord Magic Set".to_string(),
                offset: 17,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Priest Magic Set".to_string(),
                offset: 18,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Dark Priest Magic Set".to_string(),
                offset: 19,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Princess Magic Set".to_string(),
                offset: 20,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Paladin Magic Set".to_string(),
                offset: 21,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Astromancer Magic Set".to_string(),
                offset: 22,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Vartan Magic Set".to_string(),
                offset: 23,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "White Knight Magic Set".to_string(),
                offset: 24,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Shaman Magic Set".to_string(),
                offset: 25,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Wicce Magic Set".to_string(),
                offset: 26,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Songstress Magic Set".to_string(),
                offset: 27,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Knight Commander Magic Set".to_string(),
                offset: 28,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Phoenix Magic Set".to_string(),
                offset: 29,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
            FieldDefinition {
                name: "Rukh Magic Set".to_string(),
                offset: 30,
                size: 1,
                field_type: FieldType::Uint,
                options: None,
            },
        ],
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn metadata() {
        let def = definition();
        assert_eq!(def.id, "spell_access");
        assert_eq!(def.dat_file, DatFile::BattleData);
        assert_eq!(def.base_offset, 0x4AEA30);
        assert_eq!(def.entry_count, 264);
        assert_eq!(def.entry_size, 64);
    }

    #[test]
    fn field_count() {
        assert_eq!(definition().fields.len(), 31);
    }

    #[test]
    fn entry_names_count() {
        let def = definition();
        assert_eq!(def.entry_names.len(), 264);
    }

    #[test]
    fn first_field() {
        let f = &definition().fields[0];
        assert_eq!(f.name, "All Magic Set");
        assert_eq!(f.offset, 0);
        assert_eq!(f.size, 1);
    }

    #[test]
    fn last_field() {
        let f = &definition().fields[30];
        assert_eq!(f.name, "Rukh Magic Set");
        assert_eq!(f.offset, 30);
        assert_eq!(f.size, 1);
    }

    #[test]
    fn fields_within_entry_bounds() {
        let def = definition();
        for field in &def.fields {
            assert!(
                field.offset + field.size <= def.entry_size,
                "field '{}' at offset {} + size {} exceeds entry_size {}",
                field.name,
                field.offset,
                field.size,
                def.entry_size
            );
        }
    }
}
